name: Build and Push to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      IMAGE_NAME: todo-get-tasks-api
      IMAGE_TAG: v1
      ACR_NAME: acr028
      ACR_LOGIN_SERVER: acr028.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: b0151d1f-06be-43a6-9869-0ceef94ce1a5
          tenant-id: 57464fa0-05a4-4855-a9af-e5be611b8553
          subscription-id: 635e9286-14d1-435f-b7e1-af1ebf689f4e
          
      - name: Log in to ACR

        run: |
          az acr login --name $env:ACR_NAME

      - name: Build Docker Image

        run: |
          docker build `
            -t "$($env:IMAGE_NAME):$($env:IMAGE_TAG)" `
            -f GetTasksTodoMicroservice/Dockerfile `
            GetTasksTodoMicroservice

      - name: Tag Docker Image

        run: |
          docker tag `
            "$($env:IMAGE_NAME):$($env:IMAGE_TAG)" `
            "$($env:ACR_LOGIN_SERVER)/$($env:IMAGE_NAME):$($env:IMAGE_TAG)"

      - name: Push Docker Image to ACR

        run: |
          docker push "$($env:ACR_LOGIN_SERVER)/$($env:IMAGE_NAME):$($env:IMAGE_TAG)"
